version: "3"
services:
  client:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
