version: "3"
services:
  client:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
